bethel_api_schedule_all:
  defaults: 
    _controller: "BethelScheduleBundle:Schedule:all"
    _format: ~
  path: api/schedules
  requirements: 
    _method: GET
bethel_api_schedule_get: 
  defaults: 
    _controller: "BethelScheduleBundle:Schedule:get"
    _format: ~
  path: "api/schedules/{id}.{_format}"
  requirements: 
    _method: GET
    id: \d+
bethel_schedule_all: 
  defaults: 
    _controller: "BethelScheduleBundle:Schedule:all"
    _format: ~
  path: schedules
  requirements: 
    _method: GET
bethel_schedule_get: 
  defaults: 
    _controller: "BethelScheduleBundle:Schedule:get"
    _format: ~
  path: "schedules/{id}.{_format}"
  requirements: 
    _method: GET
    id: \d+
