parameters:
#    bethel_schedule.example.class: Bethel\ScheduleBundle\Example

services:
#    bethel_schedule.example:
#        class: %bethel_schedule.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
