<?php

namespace Bethel\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseCodeRepository extends EntityRepository {
    public function getCourseCodeInSession(Session $session, CourseCode $courseCode) {
        $qb = $this->createQueryBuilder('cc');
        $qb
            ->select('cc')
            ->innerJoin('cc.sessions', 's')
            ->where('s = :session')
            ->andWhere($qb->expr()->in('cc', ':courseCode'))
            ->setParameter('session', $session)
            ->setParameter('courseCode', $courseCode);

        return $qb->getQuery()->getResult();
    }

    public function getCourseCodesForActiveSemesterQB() {
        $qb = $this->createQueryBuilder('cc');
        $qb
            ->select('cc')
            ->innerJoin('cc.courses', 'c')
            ->innerJoin('c.semester', 's')
            ->where('s.active = true');

        return $qb;
    }

    public function getActiveCourseCodes() {
        $qb = $this->createQueryBuilder('cc');
        $qb
            ->select('cc')
            ->where('cc.active = true');

        return $qb->getQuery()->getResult();
    }
}