<?php

namespace Bethel\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleRepository extends EntityRepository {

    /**
     * Queries for sessions in a given semester and returns the associated schedules
     *
     * @param Semester $semester
     * @return array
     */
    public function getSemesterSchedules(Semester $semester) {
        $qb = $this->createQueryBuilder('sc')
            ->innerJoin('sc.sessions', 's')
            ->where('s.semester = :semester')
            ->setParameter('semester', $semester);

        return $qb->getQuery()->getResult();
    }
}
