imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: twig.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name: "%session.name%"
    fragments:       ~
    http_method_override: true
    #translator: { fallbacks: [en] }


# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles: [ BethelFrontBundle, BethelScheduleViewBundle, BethelCourseViewBundle, BethelSessionViewBundle, BethelUserViewBundle, BethelReportViewBundle, BethelTutorBundle, BethelEmailBundle ]
    ruby: %ruby_path%
    filters:
        cssrewrite: ~
        compass:
            bin: /usr/local/bin/compass
            load_paths:
                - "%kernel.root_dir%/../vendor/zurb/foundation/scss"

        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        entity_listener_resolver: bethel.entity_listener_resolver
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        filters:
            softdeleteable:
              class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
              enabled: true

doctrine_migrations:
    dir_name: %kernel.root_dir%/../src/Bethel/EntityBundle/Migrations
    namespace: Bethel\EntityBundle\Migrations
    table_name: migration_versions
    name: %app.title% Migrations

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

monolog:
    handlers:
        applog:
            type: stream
            path: "%monolog.applog%"
            level: error
        main:
            type: fingers_crossed
            action_level: warning
            handler: file
        file:
            type: stream
            level: debug

fos_rest:
    view:
        view_response_listener: force
    body_listener: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json','html','xml','text/css','*/*'], fallback_format: json, prefer_extension: true }

fos_js_routing:
    routes_to_expose: [ bethel_user_delete, bethel_user_get, bethel_schedule_get, bethel_semester_year_get, bethel_semester_active_get, bethel_semester_view_get, bethel_session_tutors_get, tutor_session ]

#sensio_framework_extra:
#    view:    { annotations: false }

#be_simple_sso_auth:
#    admin_sso:
#        protocol:
#            id: cas
#            version: 2
#        server:
#            id: cas
#            login_url: "%cas.login%"
#            logout_url: "%cas.logout%"
#            validation_url: "%cas.validate%"

l3_cas:
    host: "%cas.login%"               # Cas Server
    path: ~                                             # App path if not in root (eg. cas.test.com/cas)
    port: 443                                          # Server port
    ca: false                                           # SSL Certificate
    handleLogoutRequest: true                           # Single sign out activation (default: false)
    casLogoutTarget: "%cas.logout%"    # Redirect path after logout
    force: true                                         # Allows cas check mode and not force, user : __NO_USER__ if not connected (If force false, Single sign out cant work).
