bethel_course_view:
  prefix: /
  resource: "@BethelCourseViewBundle/Controller/"
  type: annotation
bethel_email: 
  prefix: /
  resource: "@BethelEmailBundle/Controller/"
  type: annotation
bethel_entity: 
  prefix: /
  resource: "@BethelEntityBundle/Controller/"
  type: annotation
bethel_front: 
  prefix: /
  resource: "@BethelFrontBundle/Controller/"
  type: annotation
bethel_report_view: 
  prefix: /
  resource: "@BethelReportViewBundle/Controller/"
  type: annotation
bethel_schedule: 
  resource: "@BethelScheduleBundle/Resources/config/routing.yml"
  type: rest
bethel_schedule_view: 
  prefix: /
  resource: "@BethelScheduleViewBundle/Controller/"
  type: annotation
bethel_semester_api: 
  resource: "@BethelSemesterApiBundle/Resources/config/routing.yml"
bethel_session: 
  resource: "@BethelSessionBundle/Resources/config/routing.yml"
  type: rest
bethel_session_view: 
  prefix: /
  resource: "@BethelSessionViewBundle/Controller/"
  type: annotation
bethel_tutor: 
  prefix: /
  resource: "@BethelTutorBundle/Controller/"
  type: annotation
bethel_user: 
  resource: "@BethelUserBundle/Resources/config/routing.yml"
  type: rest
bethel_user_view: 
  prefix: /
  resource: "@BethelUserViewBundle/Controller/"
  type: annotation
fos_js_routing: 
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
login: 
  path: /login
logout: 
  path: /logout
