services:
  bethel.apikey_authenticator:
    arguments:
      - "@bethel.sso_user_provider"
    class: Bethel\FrontBundle\Security\ApiKeyAuthenticator
  bethel.create_email:
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@swiftmailer.mailer.default"
      - "%app.title%"
      - "@request_stack"
    class: Bethel\EmailBundle\Form\Handler\EmailCreateFormHandler
  bethel.create_or_update_course_code:
    arguments:
      - "@doctrine.orm.entity_manager"
    class: Bethel\CourseViewBundle\Services\CreateOrUpdateCourseCode
  bethel.entity_listener_resolver:
    arguments:
      - "@service_container"
    class: Bethel\EntityBundle\EventListener\ListenerResolver
  bethel.populate_course:
    arguments:
      - "@doctrine.orm.entity_manager"
    class: Bethel\CourseViewBundle\Services\PopulateCourseService
  bethel.populate_course_codes:
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@session"
      - "@bethel.wsapi_controller"
      - "@bethel.populate_course"
      - "@bethel.populate_semester"
      - "@bethel.populate_professor"
    class: Bethel\CourseViewBundle\Services\PopulateCourseCodesService
  bethel.populate_courses:
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@bethel.populate_semester"
      - "@bethel.populate_professor"
      - "@bethel.populate_course"
    class: Bethel\CourseViewBundle\Services\PopulateCoursesService
  bethel.populate_professor:
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@session"
      - "@bethel.wsapi_controller"
    class: Bethel\EntityBundle\Services\PopulateProfessorService
  bethel.populate_semester:
    arguments:
      - "@doctrine.orm.entity_manager"
    class: Bethel\EntityBundle\Services\PopulateSemesterService
  bethel.session_close:
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@bethel.session_email"
    class: Bethel\SessionViewBundle\Services\SessionClose
  bethel.session_email:
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@swiftmailer.mailer.default"
      - "@twig"
      - "%app.title%"
    class: Bethel\ReportViewBundle\Services\SessionEmail
  bethel.sso_user_provider:
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@bethel.user_metadata"
      - "%bethel.apikey%"
    class: Bethel\EntityBundle\Entity\UserRepository
  bethel.user_metadata:
#    arguments:
#      - "@Bethel/EntityBundle/Entity/User"
    tags:
       name: Bethel\EntityBundle\Entity\User
    class: Doctrine\ORM\Mapping\ClassMetadata
  bethel.validate_course_code:
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@bethel.wsapi_controller"
    class: Bethel\CourseViewBundle\Services\ValidateCourseCode
  bethel.wsapi_controller:
    arguments:
      - "%wsapi.baseurl%"
      - "%wsapi.secret%"
      - "%wsapi.account_id%"
      - "%wsapi.get_username_url%"
      - "%wsapi.get_course_code_and_name_url%"
      - "%wsapi.get_courses_by_course_code_url%"
      - "%wsapi.get_courses_url%"
      - "%wsapi.get_names_url%"
    class: Bethel\WSAPIBundle\Controller\WSAPIController
  bethel_entity.session_listener:
    class: Bethel\EntityBundle\EventListener\SessionListener
    tags:
      -
        event: onFlush
        name: doctrine.event_listener
  bethel_entity.user_listener:
    arguments:
      - "@bethel.wsapi_controller"
    class: Bethel\EntityBundle\EventListener\UserListener
    tags:
      -
        name: doctrine.orm.entity_listener
      -
        entity_manager: custom
        name: doctrine.orm.entity_listener
  course_code_form_handler:
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@request_stack"
      - "@session"
      - "@bethel.populate_course_codes"
    class: Bethel\EntityBundle\Form\Handler\CourseCodeFormHandler
  gedmo.listener.softdeleteable:
    calls:
      -
        - setAnnotationReader
        -
          - "@annotation_reader"
    class: Gedmo\SoftDeleteable\SoftDeleteableListener
    tags:
      -
        connection: default
        name: doctrine.event_subscriber
  kernel.listener.open_session_listener:
    arguments:
      - "%session.name%"
      - "%cas.logout%"
    class: Bethel\SessionViewBundle\EventListener\OpenSessionListener
    tags:
      -
        event: kernel.request
        method: onKernelRequest
        name: kernel.event_listener
      -
        event: kernel.response
        method: onKernelResponse
        name: kernel.event_listener
  schedule_form_handler:
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@request_stack"
      - "@session_form_handler"
    class: Bethel\EntityBundle\Form\Handler\ScheduleFormHandler
  semester_form_handler:
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@request_stack"
      - "@session"
      - "@validator"
      - "@bethel.populate_course_codes"
    class: Bethel\EntityBundle\Form\Handler\SemesterFormHandler
  session_comment_form_handler:
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@request_stack"
    class: Bethel\EntityBundle\Form\Handler\SessionCommentFormHandler
  session_form_handler:
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@request_stack"
    class: Bethel\EntityBundle\Form\Handler\SessionFormHandler
  session_semester:
    arguments:
      - "@doctrine.orm.entity_manager"
    class: Bethel\FrontBundle\Services\SessionSemester
  term_validator:
    arguments:
      - "%app.terms%"
    class: Bethel\EntityBundle\Validator\TermValidator
    tags:
      -
        alias: term_validator
        name: validator.constraint_validator
  tutor_session_form_handler:
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@request_stack"
      - "@session"
    class: Bethel\EntityBundle\Form\Handler\TutorSessionFormHandler
  user_admin_form_handler:
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@request_stack"
    class: Bethel\EntityBundle\Form\Handler\UserAdminFormHandler
  user_create_form_handler:
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@request_stack"
      - "@bethel.wsapi_controller"
    class: Bethel\EntityBundle\Form\Handler\UserCreateFormHandler
  user_search_form_handler:
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@request_stack"
      - "@bethel.wsapi_controller"
    class: Bethel\EntityBundle\Form\Handler\UserSearchFormHandler
