parameters:
#    bethel_session.example.class: Bethel\SessionBundle\Example

services:
#    bethel_session.example:
#        class: %bethel_session.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
